
# General consts
ENCODING = "utf-8"
PORT_TO_CONNECT = 9090
MESSAGE_SIZE = 4096

# Request Consts
MESSAGE = 1
COMMAND = 2

# Command to server Consts
AUTHENTICATE_USER = 1
REGISTER_USER = 2
DELETE_USER = 3

# Database consts
WRONG_PASSWORD = -1
WRONG_LOGIN = 0
USER_ALREADY_EXIST = 0

# Server response
AUTHENTICATION_SUCCESS = 1
REGISTRATION_SUCCESS = 2
NOT_AUTHENTICATED = 3
