
# General consts
ENCODING = "utf-8"
SERVER_ADDRESS = '127.0.0.1'
PORT_TO_CONNECT = 9090
MESSAGE_SIZE = 4096
MESSAGE_DATA_SIZE = 20
MESSAGE_DATA_ITEMS_COUNT = 4
SERVER_ID = 0
USER_NOT_AUTHENTICATED = 0
SYMMETRIC_KEY_LEN_IN_BYTES = 32  # 256 bit length key is enough
AES_NONCE_LENGTH_IN_BYTES = 16
RSA_KEY_LEN_IN_BITS = 2048

# ключ известный всем на свете, костыль нужный для аутентификации пользователя и сервера, во время ssl соединения,
# а также для подписи не секретных сообщений, т.к. симметричный ключ может быть не установлен, между парой пользователей
NOT_SECRET_KEY = b'sixteen byte key'


# database consts (<=0)
DB_USER_NOT_EXIST = -4
DB_WRONG_PASSWORD = -1
DB_WRONG_LOGIN = 0
DB_USER_ALREADY_EXIST = 0

# Request consts
MESSAGE = 1
COMMAND = 2
FILE = 3
BYTES_COMMAND = 4
MESSAGE_ERROR = 5
ID_ERROR = 6

# Command to server consts
CLIENT_LOG_IN = 1
CLIENT_REGISTER_USER = 2
CLIENT_DELETE_USER = 3
CLIENT_ADD_FRIEND_BY_LOGIN = 4
CLIENT_ADD_FRIEND_BY_ID = 5
CLIENT_LOG_OUT = 6
CLIENT_GET_MESSAGES = 7
CLIENT_CREATE_P2P_CONNECTION = 8
CLIENT_SYMMETRIC_KEY_EXCHANGE = 9
CLIENT_SHUTDOWN = 10

# command for client and gui, they must not intersect with commands to server from client and server responses
GUI_FRIEND_ITEM = -1
GUI_INIT_DONE = -2
GUI_MESSAGE_ITEM = -3
GUI_CONNECTION_NOT_ESTABLISHED = -4
GUI_USER_LOG_OUT = -5
GUI_P2P_CONNECTION_DONE = -6
GUI_P2P_CONNECTION_FAIL = -7
GUI_SECRET_KEY_NOT_STATED = -8
GUI_BAD_PASSWORD_OR_LOGIN = -9
GUI_CLIENT_ERROR = -10
GUI_KEY_STATED = -11

# Server response
SERVER_WRONG_LOGIN = 1
SERVER_WRONG_PASSWORD = 2
SERVER_USER_ALREADY_EXIST = 3
SERVER_AUTHENTICATION_SUCCESS = 4
SERVER_REGISTRATION_SUCCESS = 5
SERVER_NOT_AUTHENTICATED = 6

SERVER_USER_NOT_EXIST = 7
SERVER_FRIEND_DATA = 8
SERVER_USER_OFFLINE = 9

P2P_TCP = 10
P2P_UDP = 11
P2P_CONNECTION_TYPE = 12
P2P_ADDRESS = 13
P2P_CONNECTION_DATA = 14

SERVER_SYMMETRIC_KEY = 15
SERVER_MESSAGE_FROM_DATABASE = 16
SERVER_MESSAGE_KEY_FROM_DATABASE = 17
SERVER_SECRET_MESSAGE_FROM_DATABASE = 18
SERVER_ALL_MESSAGES_SENT = 19
