
# General consts
ENCODING = "utf-8"
PORT_TO_CONNECT = 9090
MESSAGE_SIZE = 4096

# Request Consts
MESSAGE = 1
COMMAND = 2

# Command to server Consts
AUTHENTICATE_USER = 1
REGISTER_USER = 2
DELETE_USER = 3
GET_USER_ID_BY_LOGIN = 4
LOG_OUT = 5
GET_PENDING_MESSAGES = 6

# database_consts (<=0)
DB_USER_NOT_EXIST = -4
DB_WRONG_PASSWORD = -1
DB_WRONG_LOGIN = 0
DB_USER_ALREADY_EXIST = 0

# Server response
WRONG_LOGIN = 1
WRONG_PASSWORD = 2
USER_ALREADY_EXIST = 3
AUTHENTICATION_SUCCESS = 4
REGISTRATION_SUCCESS = 5
NOT_AUTHENTICATED = 6
USER_NOT_EXIST = 7
USER_FOUND = 8

